trigger:
- BeGO

resources:
- repo: self

variables:

  dockerRegistryServiceConnection: 'c79322af-4fc2-4903-91e4-7f495d80d969'
  imageRepository: 'tranhnguyenbego'
  containerRegistry: 'acrforaksanhnt315.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'acrforaksanhnt31547216aa2-auth'



stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      pool-local
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    # - upload: manifests
    #   artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      pool-local
    environment: 'tranhnguyen058bego-1854.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Agent.HomeDirectory)/TestBE/back_end_svc/be_deployment.yml
                $(Agent.HomeDirectory)/TestBE/back_end_svc/go_service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

