apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      env: staging
  template:
    metadata:
      labels:
        app: backend
        env: staging
    spec:
      containers:
      - name: backend
        image: acrforaksanhnt315.azurecr.io/tranhnguyenbego
        ports:
        - containerPort: 8080
        


